from pathlib import Path
import math, random, struct, wave, sys

class SoundManager:
    """Procedurally generated wood-like chess sounds. No third-party assets."""
    def __init__(self, root, enabled=True, volume=80):
        self.root=Path(root)/'sounds'; self.root.mkdir(parents=True,exist_ok=True)
        self.enabled=enabled; self.volume=max(0,min(100,int(volume))); self._ensure()
    def configure(self, enabled=None, volume=None):
        if enabled is not None:self.enabled=bool(enabled)
        if volume is not None:self.volume=max(0,min(100,int(volume)))
    def _make(self,path,kind):
        rate=22050; dur={'move':.095,'capture':.14,'check':.17,'castle':.18,'promotion':.20,'illegal':.13,'start':.22,'end':.26,'tick':.045}.get(kind,.1)
        n=int(rate*dur); rnd=random.Random('acs-'+kind); vals=[]
        base={'move':150,'capture':105,'check':420,'castle':125,'promotion':520,'illegal':75,'start':260,'end':180,'tick':900}.get(kind,180)
        for i in range(n):
            t=i/rate; env=math.exp(-t*(30 if kind!='tick' else 75)); noise=(rnd.random()*2-1)
            tone=math.sin(2*math.pi*base*t)+.35*math.sin(2*math.pi*base*2.18*t)
            sample=int(32767*.55*env*(.62*noise+.38*tone)); vals.append(max(-32768,min(32767,sample)))
        with wave.open(str(path),'wb') as w:
            w.setnchannels(1);w.setsampwidth(2);w.setframerate(rate);w.writeframes(b''.join(struct.pack('<h',x) for x in vals))
    def _ensure(self):
        for k in ('move','capture','check','castle','promotion','illegal','start','end','tick'):
            p=self.root/(k+'.wav')
            if not p.exists(): self._make(p,k)
        credits=self.root/'CREDITS.txt'
        if not credits.exists(): credits.write_text('Accessible Chess Stage 1 sound set\nProcedurally generated by project code; no third-party recordings or copyrighted Fritz/Lichess assets are included.\n',encoding='utf-8')
    def _scaled(self, src):
        if self.volume>=99:return src
        dst=self.root/(src.stem+f'_v{self.volume}.wav')
        if dst.exists():return dst
        with wave.open(str(src),'rb') as r:
            params=r.getparams(); frames=r.readframes(r.getnframes())
        samples=struct.unpack('<'+'h'*(len(frames)//2),frames); fac=self.volume/100
        out=b''.join(struct.pack('<h',int(s*fac)) for s in samples)
        with wave.open(str(dst),'wb') as w:w.setparams(params);w.writeframes(out)
        return dst
    def play(self,kind):
        if not self.enabled or self.volume<=0 or sys.platform!='win32':return
        try:
            import winsound
            p=self._scaled(self.root/(kind+'.wav'))
            winsound.PlaySound(str(p),winsound.SND_FILENAME|winsound.SND_ASYNC|winsound.SND_NODEFAULT)
        except Exception: pass
