from __future__ import annotations

"""Presentation adapter for the central Accessible Chess action registry.

The UI may localize labels and project registry contexts to concrete WebView
interaction scopes, but action IDs, defaults and aliases come from
:mod:`acs.keybindings`. This keeps the Web UI from becoming a second source
of truth for keyboard behavior.
"""

from typing import Any

from .keybindings import ActionRegistry, BindingContext, SCHEMA_VERSION


_UI_CONTEXT = {
    BindingContext.GLOBAL: "document",
    BindingContext.DOCUMENT: "document",
    BindingContext.HISTORY: "document",
    BindingContext.ANALYSIS: "analysis",
    BindingContext.BOARD: "board",
    BindingContext.MOVE_ENTRY: "move-entry",
    BindingContext.POSITION_EDITOR: "position-editor",
    BindingContext.ENGINE_GAME: "engine-game",
    BindingContext.DATABASE: "database",
    BindingContext.BOOK_READER: "book-reader",
    BindingContext.PGN_TREE: "pgn_tree",
    BindingContext.LIBRARY_RESULTS: "library_results",
    BindingContext.EDUCATION_LIST: "education_list",
    BindingContext.CLASSROOM_LIST: "classroom_list",
    BindingContext.TOOLBAR: "toolbar",
    BindingContext.PROFILE_DIALOG: "profile_dialog",
}

_UK_LABELS = {
    "screen.board": "Дошка та партія",
    "screen.analysis": "Аналіз",
    "screen.pgn": "PGN та дерево партії",
    "screen.library": "Бібліотека та пошук",
    "screen.books": "Книги",
    "screen.training": "Тренування",
    "screen.teacher": "Режим викладача",
    "screen.classes": "Класи та учні",
    "screen.settings": "Налаштування",
    "screen.help": "Довідка",
    "history.previous": "Попередня позиція в історії",
    "history.next": "Наступна позиція в історії",
    "history.go_to_move": "Перейти до ходу",
    "history.commit_go_to_move": "Підтвердити перехід до введеного ходу",
    "file.new": "Нова стандартна позиція",
    "edit.undo": "Скасувати хід",
    "edit.redo": "Повторити хід",
    "analysis.pv1": "Перший варіант Stockfish",
    "analysis.pv2": "Другий варіант Stockfish",
    "analysis.pv3": "Третій варіант Stockfish",
    "analysis.pv4": "Четвертий варіант Stockfish",
    "analysis.pv5": "П’ятий варіант Stockfish",
    "analysis.previous_pv": "Попередній варіант Stockfish",
    "analysis.next_pv": "Наступний варіант Stockfish",
    "analysis.lock_target": "Зафіксувати ціль аналізу або стежити за позицією",
    "analysis.explore_pv": "Тимчасово переглянути вибраний варіант",
    "analysis.return": "Повернутися з тимчасового варіанта",
    "analysis.insert_move": "Вставити вибраний хід Stockfish",
    "analysis.insert_line": "Вставити вибраний варіант Stockfish",
    "analysis.restart": "Перезапустити аналіз Stockfish",
    "board.cursor_left": "Курсор дошки ліворуч",
    "board.cursor_right": "Курсор дошки праворуч",
    "board.cursor_up": "Курсор дошки вгору",
    "board.cursor_down": "Курсор дошки вниз",
    "board.activate": "Активувати поле дошки",
    "board.activate_alternative": "Активувати поле дошки, альтернативна клавіша",
    "board.exit": "Вийти з дошки",
    "board.current": "Поточне поле",
    "board.last_captured": "Остання взята фігура",
    "board.last_move": "Останній хід",
    "board.my_clock": "Мій час",
    "board.opponent_clock": "Час суперника",
    "board.legal_moves": "Легальні ходи",
    "board.captures": "Взяття",
    "board.surroundings": "Оточення поля",
    "board.attackers": "Атакуючі",
    "board.defenders": "Захисники",
    "board.material": "Матеріальний баланс",
    "board.evaluation": "Оцінка позиції",
    "board.best_move": "Найкращий хід",
    "board.play_best": "Зіграти найкращий хід",
    "board.next_king": "Наступний король",
    "board.next_queen": "Наступний ферзь",
    "board.next_rook": "Наступна тура",
    "board.next_bishop": "Наступний слон",
    "board.next_knight": "Наступний кінь",
    "board.next_pawn": "Наступний пішак",
    "board.previous_king": "Попередній король",
    "board.previous_queen": "Попередній ферзь",
    "board.previous_rook": "Попередня тура",
    "board.previous_bishop": "Попередній слон",
    "board.previous_knight": "Попередній кінь",
    "board.previous_pawn": "Попередній пішак",
    "board.input": "Поле введення ходу",
    "move.submit": "Зробити введений хід",
    "move.undo": "Команда undo",
    "move.redo": "Команда redo",
    "move.last": "Команда останнього ходу",
    "move.white_to_move": "Команда ходу білих",
    "move.black_to_move": "Команда ходу чорних",
    "move.clear": "Команда очищення дошки",
    "move.standard": "Команда стандартної позиції",
    "move.empty": "Команда порожньої позиції",
    "pgn.previous_item": "Попередній елемент дерева PGN",
    "pgn.open": "Відкрити PGN",
    "pgn.save": "Зберегти PGN",
    "pgn.save_as": "Зберегти PGN як",
    "pgn.open_on_board": "Переглянути PGN на дошці",
    "pgn.return": "Повернутися до PGN",
    "pgn.board_next_move": "Наступний хід PGN на дошці",
    "pgn.board_previous_move": "Попередній хід PGN на дошці",
    "pgn.board_enter_variation": "Увійти у варіант PGN на дошці",
    "pgn.board_leave_variation": "Вийти з варіанта PGN на дошці",
    "pgn.select_item": "Вибрати елемент дерева партії",
    "pgn.previous_game": "Попередня партія PGN",
    "pgn.next_game": "Наступна партія PGN",
    "pgn.first_child": "Перший дочірній елемент дерева партії",
    "pgn.first_item": "Перший елемент дерева партії",
    "pgn.last_item": "Останній елемент дерева партії",
    "pgn.comment_edit": "Додати або змінити коментар дерева партії",
    "pgn.comment_delete": "Видалити коментар дерева партії",
    "pgn.variation_delete": "Видалити варіант",
    "pgn.variation_promote": "Зробити варіант головним",
    "pgn.copy_selection": "Копіювати вибрану партію або варіант",
    "pgn.export_selection": "Експортувати вибрану партію або варіант",
    "pgn.next_item": "Наступний елемент дерева PGN",
    "pgn.parent_variation": "Повернутися до батьківського варіанта",
    "library.previous_result": "Попередній результат бібліотеки",
    "library.next_result": "Наступний результат бібліотеки",
    "library.first_result": "Перший результат бібліотеки",
    "library.last_result": "Останній результат бібліотеки",
    "library.open_game": "Відкрити вибрану партію з бібліотеки",
    "library.search": "Шукати в бібліотеці",
    "library.reset_filters": "Скинути фільтри бібліотеки",
    "library.next_page": "Наступна сторінка бібліотеки",
    "library.previous_page": "Попередня сторінка бібліотеки",
    "library.import": "Імпортувати до бібліотеки",
    "library.cancel_import": "Скасувати операцію бібліотеки",
    "library.export": "Експортувати з бібліотеки",
    "book.open": "Відкрити книгу",
    "book.board_next_move": "Наступний хід партії з книги",
    "book.board_previous_move": "Попередній хід партії з книги",
    "book.board_enter_variation": "Увійти у варіант партії з книги",
    "book.board_leave_variation": "Вийти з варіанта партії з книги",
    "book.board_analyze": "Аналізувати позицію з книги",
    "book.previous_block": "Попередній блок книги",
    "book.next_block": "Наступний блок книги",
    "book.previous_heading": "Попередній заголовок книги",
    "book.next_heading": "Наступний заголовок книги",
    "book.previous_position": "Попередня позиція книги",
    "book.next_position": "Наступна позиція книги",
    "book.previous_game": "Попередня партія книги",
    "book.next_game": "Наступна партія книги",
    "book.bookmark": "Зберегти місце повернення до книги",
    "book.open_position": "Відкрити позицію книги на дошці",
    "book.open_game": "Відкрити партію книги на дошці",
    "book.return": "Повернутися до книги",
    "training.submit": "Надіслати відповідь тренування",
    "training.hint": "Підказка тренування",
    "training.reveal_solution": "Показати розв’язок тренування",
    "training.retry": "Повторити крок тренування",
    "training.reset": "Скинути вправу тренування",
    "teacher.pointer_input": "Ввести вказівник викладача",
    "teacher.pointer_clear": "Очистити вказівник викладача",
    "teacher.highlight": "Виділити поле",
    "teacher.arrow": "Додати навчальну стрілку",
    "teacher.clear_annotations": "Очистити навчальні позначки",
    "teacher.coordinates_toggle": "Увімкнути або вимкнути навчальні координати",
    "teacher.orientation_toggle": "Змінити орієнтацію дошки",
    "teacher.board_permission": "Налаштувати дозвіл учня на дошку",
    "teacher.engine_visibility": "Налаштувати видимість навчального рушія",
    "teacher.read_student_event": "Прочитати останню подію учня",
    "teacher.prepared_previous": "Попередня підготовлена навчальна позиція",
    "teacher.prepared_next": "Наступна підготовлена навчальна позиція",
    "teacher.rotation_start_or_resume": "Почати або продовжити групову ротацію",
    "teacher.rotation_advance": "Перейти до наступного кроку групової ротації",
    "teacher.rotation_bind_pairing": "Прив’язати поточні пари до ротації",
    "teacher.rotation_status": "Прочитати стан групової ротації",
    "student.move": "Надіслати явний хід учня",
    "classes.new": "Новий клас",
    "classes.open": "Відкрити клас",
    "classes.student_open": "Відкрити учня",
    "classes.lesson_open": "Відкрити урок",
    "classes.assignment_open": "Відкрити завдання",
    "remote.connect": "Приєднатися до спільного уроку",
    "remote.reconnect": "Повторно приєднатися до спільного уроку",
    "remote.leave": "Вийти зі спільного уроку",
    "education.previous_item": "Попередній навчальний елемент",
    "education.next_item": "Наступний навчальний елемент",
    "education.open_selected": "Відкрити вибраний навчальний елемент",
    "classroom.previous_item": "Попередній елемент класу",
    "classroom.next_item": "Наступний елемент класу",
    "classroom.first_item": "Перший елемент класу",
    "classroom.last_item": "Останній елемент класу",
    "classroom.open_selected": "Відкрити вибраний елемент класу",
    "toolbar.previous_control": "Попередній елемент панелі інструментів",
    "toolbar.next_control": "Наступний елемент панелі інструментів",
    "toolbar.first_control": "Перший елемент панелі інструментів",
    "toolbar.last_control": "Останній елемент панелі інструментів",
    "profile.save_name": "Зберегти ім’я локального профілю",
}

_EN_LABELS: dict[str, str] = {
    "screen.help": "Help",
    "history.commit_go_to_move": "Confirm typed history move",
    "move.submit": "Submit move",
    "board.cursor_left": "Move board cursor left",
    "board.cursor_right": "Move board cursor right",
    "board.cursor_up": "Move board cursor up",
    "board.cursor_down": "Move board cursor down",
    "board.activate": "Activate board square",
    "board.activate_alternative": "Activate board square, alternative key",
    "board.exit": "Exit board interaction",
    "classroom.previous_item": "Previous classroom item",
    "classroom.next_item": "Next classroom item",
    "classroom.first_item": "First classroom item",
    "classroom.last_item": "Last classroom item",
    "classroom.open_selected": "Open selected classroom item",
    "toolbar.previous_control": "Previous toolbar control",
    "toolbar.next_control": "Next toolbar control",
    "toolbar.first_control": "First toolbar control",
    "toolbar.last_control": "Last toolbar control",
    "profile.save_name": "Save local profile name",
}

for _number in range(1, 9):
    _file = "abcdefgh"[_number - 1]
    _UK_LABELS[f"board.rank_{_number}"] = f"Горизонталь {_number}"
    _UK_LABELS[f"board.file_{_number}"] = f"Вертикаль {_file}"
    _EN_LABELS[f"board.rank_{_number}"] = f"Rank {_number}"
    _EN_LABELS[f"board.file_{_number}"] = f"File {_file}"


def build_web_keymap(registry: ActionRegistry | None = None) -> dict[str, Any]:
    registry = registry or ActionRegistry()
    actions: list[dict[str, Any]] = []
    for definition in registry.definitions():
        if definition.external:
            continue
        actions.append(
            {
                "id": definition.action_id,
                "context": _UI_CONTEXT[definition.context],
                "registryContext": definition.context.value,
                "labelUk": _UK_LABELS.get(definition.action_id, definition.title),
                "labelEn": _EN_LABELS.get(definition.action_id, definition.title),
                "binding": registry.get_binding(definition.action_id),
                "alias": registry.get_alias(definition.action_id),
                "defaultBinding": definition.default_binding,
                "defaultAlias": definition.default_alias,
            }
        )
    return {"schemaVersion": SCHEMA_VERSION, "actions": actions}
